#:schema node_modules/wrangler/config-schema.json
name = "discohook-utils-redirection-routes"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[env.preview]
name = "discohook-utils-redirection-routes-preview"

[env.preview.vars]
DISCOHOOK_ORIGIN = "https://preview.discohook.app"

[env.production]
route = { pattern = "dutils.shay.cat", custom_domain = true }

[env.production.vars]
DISCOHOOK_ORIGIN = "https://discohook.app"
